################################################################################
# MIT License
# 
# Copyright (c) 2025 Advanced Micro Devices, Inc. All Rights Reserved.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
################################################################################

name: "IntelliPerf Action"
description: "A GitHub Action wrapper for IntelliPerf"
inputs:
  formula:
    description: "Global IntelliPerf formula to use for all applications (can be overridden per application)"
    required: false
  build_command:
    description: "Global build command to use for all applications (can be overridden per application)"
    required: false
  instrument_command:
    description: "Global instrument command to use for all applications (can be overridden per application)"
    required: false
  project_directory:
    description: "Global project directory to use for all applications (can be overridden per application)"
    required: false
  applications:
    description: "List of application objects. Each object can have: command (required), output_json (optional), build_script (optional), build_command (optional), instrument_command (optional), project_directory (optional), formula (optional)"
    required: true
  docker_image:
    description: "Default Docker image to use"
    required: false
  apptainer_image:
    description: "Default Apptainer image to use"
    required: false
  top_n:
    description: "Top N kernels to report"
    required: false
    default: "10"
  huggingface_token:
    description: "Huggingface token"
    required: false    
  llm_gateway_key:
    description: "LLM Gateway API key for accessing language models"
    required: false
  create_pr:
    description: "Whether to create a PR with changes"
    required: false
    default: "false"
  intelliperf_actions_token:
    description: "GitHub token for PR creation (required if create_pr is true)"
    required: false    
runs:
  using: "node20"
  main: "dist/index.js"
