name: "Maestro Action"
description: "Runs Maestro"
inputs:
  formula:
    description: "Maestro Formula"
    required: true
  applications:
    description: "List of application objects"
    required: true
  docker_image:
    description: "Default Docker image to use"
    required: false
  apptainer_image:
    description: "Default Apptainer image to use"
    required: false
  top_n:
    description: "Top N kernels to report (default: 10)"
    required: false
  huggingface_token:
    description: "Huggingface token"
    required: false    
runs:
  using: "node20"
  main: "dist/index.js"
